version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    # Do unshallow git clone in RtD build to fix reno version traversal
    post_checkout:
      - git fetch --unshallow || true

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  configuration: docs/conf.py
