version: 2

jobs:

  #
  # linux
  #

  test-3.8: &test-linux-template
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
      - run: python -m virtualenv env
      - run: &install-requirements
          name: Install requirements
          command: |
            . env/bin/activate
            pip install -r tests/requirements.txt
            pip install dwave-inspectorapp --extra-index=https://pypi.dwavesys.com/simple
            pip install wheel twine
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - env
      - run: &install-package
          name: Install package
          command: env/bin/python setup.py install
      - run: &build-package
          name: Build package
          command: env/bin/python setup.py sdist bdist_wheel
      - run: &run-tests
          name: Run tests
          command: env/bin/coverage run -m unittest discover
      - run:
          name: codecov
          command: |
            . env/bin/activate
            codecov   # calls `coverage xml`, so we must activate venv

  test-3.7:
    <<: *test-linux-template
    docker:
      - image: circleci/python:3.7

  test-3.6:
    <<: *test-linux-template
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-linux-template
    docker:
      - image: circleci/python:3.5

  #
  # macos
  #

  test-osx-3.8: &test-osx-template
    macos:
      xcode: "11.2.1"
    environment:
      PYTHON: 3.8.0
    steps:
      - checkout

      # install $PYTHON and cache it
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install pyenv
      - restore_cache:
          keys:
            - pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-11.2.1
      - run: pyenv install $PYTHON -s
      - save_cache:
          key: pyenv-{{ .Environment.CIRCLE_JOB }}-xcode-11.2.1
          paths:
            - ~/.pyenv

      # install dependencies
      - run:
          name: Create virtual environment
          command: |
            eval "$(pyenv init -)"
            pyenv local $PYTHON
            python -m pip install virtualenv
            python -m virtualenv env
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}
      - run: *install-requirements
      - save_cache:
          paths:
            - env
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ .Environment.CIRCLE_JOB }}

      - run: *install-package

      - run: *run-tests

  test-osx-3.7:
    <<: *test-osx-template
    environment:
      PYTHON: 3.7.4

  test-osx-3.6:
    <<: *test-osx-template
    environment:
      PYTHON: 3.6.5

  test-osx-3.5:
    <<: *test-osx-template
    environment:
      PYTHON: 3.5.5

  #
  # deploy
  #

  pypi-deploy:
    <<: *test-linux-template
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "tests/requirements.txt" }}-test-3.8
      - run: *build-package
      - store_artifacts:
          path: dist
      - run: env/bin/twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" --skip-existing ./dist/*


workflows:
  version: 2
  test:
    jobs:
      - test-3.8
      - test-3.7
      - test-3.6
      - test-3.5
      - test-osx-3.8
      - test-osx-3.7
      - test-osx-3.6
      - test-osx-3.5

  deploy:
    jobs:
      - test-3.8:
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
      - pypi-deploy:
          requires:
            - test-3.8
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(\.dev([0-9]+)?)?$/
            branches:
              ignore: /.*/
